language: java
before_install:
   - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
   - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
deploy:
  - provider: script
    script: mvn -P publish deploy -s settings.xml 
    on:
      branch: develop
  - provider: script
    script: mvn -P publish -B release:clean release:prepare release:perform -s settings.xml
    on:
      branch: master
env:
  global:
  - secure: FOCi/L0glQHZbWt6tkRHZaYj6I32CQtHm9/abQpYNBQlusol6NQLtfO5/YcOR0kHYM9kQUKCGcHbFXEN8YGMtO+R+ob4Hz5VuGZgtAa6wcAUCL7+jaBRDmEEnLNRX991MmEKAxX2Ect0LAGtLzYytjTuZt4R7XTkeILRG6dRNjWdkXW+MdkxKtEGIknrRlC5kPGXW6fMZVyTB4EYHXSaCrH2CrExQu9yavWLxBTNGteT6rKwAExzrr74yUxxYY/DkTfsRLjb4FIkM++ulN/gwmytjxv1Wx3qPSgvv/ja0j8E3qxQwIs6jBTdUX6I5ibnL9VrlEpFC4R/zsQ82ow8Wv+cB8vK4fYUBrJKjnAdguWrYWBqrLj2dQcRbtLS8DubeDLGGF+9Yc8VarGrCjR0j49XSY25PDkletxztPdHDtYPAClou2orSc7BlxVYFoKHa+1SUgwEUUwYpfyRpRxoryDR3a/cylDFfXpGVZONbyTZzxbronvUcRos17uJ34GMKlJU4DtBsML98/9bBEwNThroeuPfbrXEpSZstQRfm378QjWhkFrzJYzwJLp0nVhqLskiQx1VGhcrKrefcNQaCA0tcTIlYeCy8mZGKwhp4vAgxKsbE8aUuUM02qjnOAd3L+IY4NAww9SSWoxUCgiOVe2L+nImJKy39ZvGsZ1nhVE=
  - secure: cTArKxSFC0oYy0PXtFTvMI5IG+T+9wVEHMpx59c2OAvjeOMZh4ppe0NlU5pO98uDboGXxMCi0zHzmVmS4apoYWD/eMGDyGb5YHnjggTWJmLpLEHafnQYXMfBKHNPRGdKUMVWh1p+2O/6RK3YrViE7J0S54irrHd+zZS7DQeqWVqq6J82WoF33Vi9aTj++zP1NLXuFrWW1bTxt81/P63Re7S3n3+j1vPQ6hP87eNZ/WBnshw438KrDbFd/L7dCsXagz3ynMdwi7PJkr4khHb57R0HmUjOTl/qTAlEc+Ik2gEVWkf6XNGUe+I9rvTlh8ZDk7M0x46VH6LYbprFVnV4+2z0V7ikWznB7T15Z7rCcLMoI7ACiB+HuIhuzIqovrPYJ2OYWq28T6iCFdlBU9V6G7dggGjPf/QogDerlYVjn62uR16zQM8j0c1grW7ziRMtzdLpsUPxjPdOBvL/wxnFfGB/H/jYMGa1XwhND9Wx3P2yR4FXkl0EorkNHzI3El7iWUoWVFfLLYnjOoMiGXDJ1pdNPFYEmpOQJ9uX+KcrxoTDnnbH84bY7fD2FX/OIm7d4jZuqqfGw/gwlJlYkUGH/O9aAcaw4DObdOXb0phsrGzMB/KGSlDZ5XsYAwCOQ5hLQ7k93l/CLFfkdsNBSl/ZyzlI/QPEgr9MWkIgFRmMe98=
